name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Manual trigger

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Haxe
      run: |
        brew install haxe
        
    - name: Setup Haxelib
      run: |
        mkdir -p ~/haxelib
        haxelib setup ~/haxelib
        
    - name: Install Core Libraries
      run: |
        haxelib install lime --quiet
        haxelib install openfl 9.2.2 --quiet
        haxelib run lime setup -y
        
    - name: Install Custom CNE Libraries (Priority Order)
      run: |
        haxelib git flixel https://github.com/CodenameCrew/cne-flixel --quiet
        haxelib git flixel-addons https://github.com/CodenameCrew/cne-flixel-addons --quiet
        haxelib install flixel-ui 2.6.1 --quiet
        
    - name: Install Additional Dependencies
      run: |
        echo "Installing hscript-improved..."
        haxelib git hscript-improved https://github.com/CodenameCrew/hscript-improved custom-classes --quiet
        echo "Installing flxanimate..."
        haxelib git flxanimate https://github.com/CodenameCrew/cne-flxanimate --quiet
        haxelib install format --quiet
        haxelib install markdown --quiet
        haxelib install nape-haxe4 --quiet
        haxelib install hxvlc 1.9.3 --quiet || echo "hxvlc not available, skipping"
        haxelib git away3d https://github.com/CodenameCrew/away3d --quiet || echo "away3d not available, skipping"
        haxelib git hxcpp https://github.com/CodenameCrew/cne-hxcpp --quiet
        echo "All dependencies installed"
        
    - name: Setup iOS
      run: |
        haxelib run lime setup ios -y
        
    - name: Create project.xml
      run: |
        cat > project.xml << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<project>
  <app
    title="Friday Night Funkin' - Codename Engine" main="funkin.backend.system.Main"
    file="CodenameEngine" packageName="com.yoshman29.codenameengine"
    package="com.yoshman29.codenameengine"
    version="0.1.0-legacy" company="Yoshman29" />

  <app save-path="YoshiCrafter29/CodenameEngine" save-name="save-default" mod-saves="true" />
  <haxedef name="REGION" />
  <app preloader="flixel.system.FlxPreloader" />
  <set name="SWF_VERSION" value="11.8" />

  <window width="1280" height="720" background="#000000" hardware="true" vsync="false" />
  <window if="html5" resizable="true" />
  <window if="desktop" orientation="landscape" fullscreen="false" resizable="true" vsync="false"/>
  <window if="mobile" orientation="landscape" fullscreen="true" width="0" height="0" resizable="false"/>

  <set name="BUILD_DIR" value="export/debug" if="debug" />
  <set name="BUILD_DIR" value="export/release" unless="debug" />
  <source name="source" />
  <assets path='assets/mobile' if='mobile'/>

  <define name="PRELOAD_ALL" unless="web" />
  <define name="NO_PRELOAD_ALL" unless="PRELOAD_ALL"/>
  <library name="assets" preload="true" if="PRELOAD_ALL"/>
  <library name="assets" preload="false" if="NO_PRELOAD_ALL" />

  <assets path="assets/" rename="assets" exclude="*.ogg" if="web"/>
  <assets path="assets/" rename="assets" exclude="*.mp3" unless="web"/>
  <assets path='mods' rename='mods' embed='false'/>

  <!-- Build configuration -->
  <haxedef name="FLX_NO_FOCUS_LOST_SCREEN" />
  <haxedef name="FLX_NO_DEBUG" unless="debug" />
  <haxedef name="ALLOW_MULTITHREADING" unless="web || flash" />
  <haxedef name="MOD_SUPPORT" unless="web"/>
  
  <!-- iOS specific fixes -->
  <haxedef name="NO_PRECOMPILED_HEADERS" />
  <haxedef name="HXCPP_SMART_STRINGS" />
  <haxedef name="mobile" if="ios" />
  <haxedef name="ios" if="ios" />
  
  <!-- Custom macros -->
  <haxeflag name="--macro" value="funkin.backend.system.macros.NewHaxeWarning.warn()" />
  <haxeflag name="--macro" value="funkin.backend.system.macros.Macros.initMacros()" />
  
  <!-- Compilation flags -->
  <haxeflag name="-dce" value="no" if="COMPILE_ALL_CLASSES" />

  <!-- App icons -->
  <icon path="art/icon16.png" size='16'/>
  <icon path="art/icon32.png" size='32'/>
  <icon path="art/icon64.png" size='64'/>
  <icon path="art/iconOG.png" />

  <!-- Platform defines -->
  <define name="DISCORD_RPC" if="desktop"/>
  <define name="GITHUB_API" unless="web || hl"/>
  <define name="COMPILE_ALL_CLASSES" />
  <define name="CUSTOM_CLASSES" />
  <define name="VIDEO_CUTSCENES" if="desktop || android" />

  <!-- Required libraries -->
  <haxelib name="flixel" />
  <haxelib name="flixel-addons" />
  <haxelib name="flixel-ui" />
  <haxelib name="format" />
  <haxelib name="flxanimate" />
  <haxelib name="hscript-improved" />
  <haxelib name="markdown" />
  <haxelib name="nape-haxe4" />
  <haxelib name="away3d" if="desktop" />
  <haxelib name="hxvlc" if="desktop" />
  <haxelib name="hxcpp" />

  <!-- Platform targets -->
  <android target-sdk-version="34" />
  <android min-sdk-version="19" />
  <ios deployment="12.0" />
</project>
EOF
        echo "Created project.xml successfully"
