name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Haxe
      run: |
        brew install haxe
        brew install lime
        brew install openfl
        haxelib setup ~/haxelib

    - name: Install and Update Haxelibs
      run: |
        haxelib install lime
        haxelib install openfl
        haxelib install flixel
        haxelib install flixel-addons
        haxelib install flixel-ui
        haxelib install hxcpp
        haxelib install hscript
        haxelib install actuate
        haxelib upgrade
        haxelib list

    - name: Build iOS App
      run: |
        haxelib run lime build ios -release -arm64
