name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    # 1. Checkout
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Select Xcode
    - name: Select Xcode 15.4
      run: sudo xcode-select --switch /Applications/Xcode_15.4.app

    # 3. Stub Haxe (bypass Build Haxe)
    - name: Stub Haxe
      run: |
        echo '#!/bin/bash' > fake-haxe.sh
        echo 'echo "Skipping Haxe build..."' >> fake-haxe.sh
        chmod +x fake-haxe.sh
        sudo mv /usr/local/bin/haxe /usr/local/bin/haxe.bak 2>/dev/null || true
        sudo cp fake-haxe.sh /usr/local/bin/haxe

    # 4. Find Xcode project
    - name: Find Xcode Project
      run: |
        xcodeproj_path=$(find . -name "*.xcodeproj" -type d | head -1)
        if [ -z "$xcodeproj_path" ]; then
          echo "ERROR: No .xcodeproj folder found!"
          ls -la
          exit 1
        fi
        echo "Found Xcode project: $xcodeproj_path"
        echo "XCODEPROJ_PATH=$xcodeproj_path" >> $GITHUB_ENV

    # 5. Build and archive
    - name: Archive iOS App
      run: |
        project_name=$(basename "$XCODEPROJ_PATH" .xcodeproj)
        echo "Archiving project: $project_name"
        xcodebuild archive \
          -project "$XCODEPROJ_PATH" \
          -scheme "CodenameEngine" \
          -configuration Release \
          -archivePath build/CodenameEngine.xcarchive \
          -destination "generic/platform=iOS" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          DEVELOPMENT_TEAM="" \
          ARCHS="arm64" \
          ONLY_ACTIVE_ARCH=NO
        echo "ARCHIVE_PATH=build/CodenameEngine.xcarchive" >> $GITHUB_ENV

    # 6. Create unsigned IPA
    - name: Create IPA
      run: |
        mkdir -p build/export/Payload
        app_path=$(find "$ARCHIVE_PATH/Products/Applications" -name "*.app" | head -1)
        if [ -z "$app_path" ]; then
          echo "No .app found in archive"
          find "$ARCHIVE_PATH" -type f
          exit 1
        fi
        cp -r "$app_path" build/export/Payload/
        cd build/export
        zip -r CodenameEngine-unsigned.ipa Payload
        cd ../..
        echo "IPA created successfully"
        ls -la build/export/

    # 7. Upload IPA
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: ios-unsigned-ipa
        path: build/export/*.ipa
        if-no-files-found: error
