name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Manual trigger

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Haxe
      run: |
        brew install haxe
        
    - name: Setup Haxelib
      run: |
        mkdir -p ~/haxelib
        haxelib setup ~/haxelib
        
    - name: Install Haxe dependencies
      run: |
        haxelib install lime
        haxelib install openfl
        haxelib install flixel
        haxelib install flixel-ui
        haxelib install flixel-addons
        haxelib git hscript-improved https://github.com/FNF-CNE-Devs/hscript-improved
        haxelib run lime setup -y
        
    - name: Setup iOS
      run: |
        haxelib run lime setup ios -y
        
    - name: Debug Project Files
      run: |
        echo "=== Current Directory ==="
        pwd
        echo "=== All Files ==="
        ls -la
        echo "=== XML Files ==="
        find . -name "*.xml" -type f
        echo "=== Project.xml Content ==="
        cat Project.xml || echo "Cannot read Project.xml"
        echo "=== File Permissions ==="
        ls -la Project.xml || echo "Project.xml not found"
        
    - name: Build iOS
      run: |
        if [ -f "Project.xml" ]; then
          echo "Project.xml exists, building..."
          haxelib run lime build ios -release
        else
          echo "Project.xml still not found!"
          exit 1
        fi
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: export/ios/build/Release-iphoneos/*.ipa
        if-no-files-found: warn
        
    - name: Upload Simulator App (fallback)
      uses: actions/upload-artifact@v4
      with:
        name: ios-simulator-app
        path: export/ios/build/Release-iphonesimulator/*.app
        if-no-files-found: ignore