name: iOS Build
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  iOS:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update all files
        run: |
          git fetch --all
          git reset --hard origin/${{ github.ref_name }}
          git clean -fd

      - name: Setup Haxe (manual)
        run: |
          brew update
          brew install haxe
          haxe --version

      - name: Install Libraries
        run: |
          haxe -cp commandline -D analyzer-optimize --run Main setup -s

      - name: Verify library versions
        run: haxelib list

      - name: Compile iOS
        run: haxelib run lime build ios -clean -nosign

      - name: Create IPA
        run: |
          cd export/release/ios/build/*-iphoneos
          mkdir Payload
          mv *.app Payload
          zip -r CodenameEngine.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CodenameEngine-iOS
          path: export/release/ios/build/Release-iphoneos/*.ipa
          if-no-files-found: error
