name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4

    - name: Setup Haxe & Libraries
      run: |
        brew install haxe
        haxelib setup ~/haxelib
        haxelib install lime
        haxelib install openfl
        haxelib install hxcpp
        if [ -f "./update.sh" ]; then
          chmod +x ./update.sh
          ./update.sh
        fi

    - name: Patch deployment target in Xcode project
      run: |
        sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 9.0;/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/g' export/release/ios/CodenameEngine.xcodeproj/project.pbxproj

    - name: Build iOS
      run: |
        haxelib run lime setup ios -y
        haxelib run lime build ios -release -nosign -Dios_deployment_target=12.0

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: export/ios/build/Release-iphoneos/*.ipa
