name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Manual trigger

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Haxe 3.4.7
      run: |
        brew uninstall haxe || true
        brew tap homebrew/cask-versions
        brew install haxe@3.4
        brew link haxe@3.4 --force
        haxe -version

    - name: Setup Haxelib
      run: |
        mkdir -p ~/haxelib
        haxelib setup ~/haxelib

    - name: Install OLD Haxe dependencies
      run: |
        haxelib install lime 2.9.1
        haxelib install openfl 3.6.1
        haxelib install flixel 4.3.0
        haxelib install flixel-ui 2.3.0
        haxelib install flixel-addons 2.6.0
        haxelib git hscript-improved https://github.com/FNF-CNE-Devs/hscript-improved
        haxelib run lime setup -y
        haxelib install away3d 1.0.0
        haxelib install format 3.3.0
        haxelib install flxanimate 3.0.4
        haxelib install nape 2.0.20
        haxelib install markdown 1.0.0

    - name: Setup iOS
      run: |
        haxelib run lime setup ios -y

    - name: Build iOS (No Signing)
      run: |
        haxelib run lime build ios -release -nosign

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: export/ios/build/Release-iphoneos/*.ipa
        if-no-files-found: warn

    - name: Upload Simulator App (fallback)
      uses: actions/upload-artifact@v4
      with:
        name: ios-simulator-app
        path: export/ios/build/Release-iphonesimulator/*.app
        if-no-files-found: ignore
